services:
  mysql:
    image: mysql:8.0
    container_name: camera_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nvr_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  flask_app:
    build: ./backend
    container_name: camera_api
    depends_on:
      - mysql
    environment:
      DATABASE_URL: "mysql+mysqlconnector://root:root@mysql/nvr_db"
    ports:
      - "5000:5000"
    restart: always

  react_app:
    build: ./react
    container_name: camera_frontend
    depends_on:
      - flask_app
    ports:
      - "3000:3000"
    restart: always

volumes:
  mysql_data:
